# Generated by Django 5.0.3 on 2024-05-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_amenity_description_alter_amenity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Превью отеля'),
        ),
    ]
