# Generated by Django 5.0.3 on 2024-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_service_options_amenity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(to='hotels.amenity', verbose_name='Удобства'),
        ),
    ]
