# Generated by Django 5.0.3 on 2024-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение номера'),
        ),
    ]
