# Generated by Django 5.0.3 on 2024-05-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
