# Generated by Django 5.0.3 on 2024-05-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_remove_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6, verbose_name='Цена за ночь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Номер на 1 персону'), ('double', 'Номер на 2 персоны'), ('suite', 'Люкс'), ('family', 'Семейный')], default='single', max_length=20, verbose_name='Тип комнаты'),
        ),
    ]
