# Generated by Django 5.0.3 on 2024-05-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_booking_price_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
    ]
