# Generated by Django 5.0.3 on 2024-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_remove_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта Гостя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(default=1, verbose_name='Имя Гостя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_number',
            field=models.CharField(default=1, verbose_name='Номер телефона Гостя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_surname',
            field=models.CharField(default=1, verbose_name='Фамилия Гостя'),
            preserve_default=False,
        ),
    ]
